networks:
  sidecar:
    driver: bridge
services:
  aeroalpes:
    container_name: aeroalpes
    hostname: aeroalpes
    image: caprilespe/aeroalpes-sidecar:1.0.0
    networks:
      - sidecar
    labels:
      SidecarDiscover: "false"
    ports:
      - "5000:5000"

  adaptador:
    image: "caprilespe/aeroalpes-adapter-sidecar:1.0.0"
    container_name: adaptador
    hostname: adaptador
    networks:
      - sidecar
    environment:
      - AEROALPES_ADDRESS=aeroalpes
    ports:
      - "50051:50051"